version: '2'
 
services:
  postgresserver:
    image: postgres:latest
    container_name: 
      db
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: "radix"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "radix-dev"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork
 
  api:
    image: radixapi
    container_name: 
      api
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile.Api
    links:
      - postgresserver
    depends_on:
      - "postgresserver"
    command: ["./wait-for-it.sh", "postgresserver:5432", "--", "python", "app.py"]  
    networks:
      - mynetwork
  ui:
    image: radix-ui:latest
    container_name: 
      ui
    depends_on:
     - "api"
    build: 
      context: .
      dockerfile: Dockerfile.Ui
    links:
      - 'api:api'
    command: ["./wait-for-it.sh", "api:5000", "--", "python", "app.py"] 
    ports: 
     - "3000:3000"
    restart: always
    environment:
      url: "http://api:5000"
    networks:
      - mynetwork

volumes:
  pgdata:
networks:
  mynetwork:
     driver: bridge